"""Agregar columna aprobado a practicas

Revision ID: 198efedbf2db
Revises: f25299a1a321
Create Date: 2025-05-01 19:00:02.592855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '198efedbf2db'
down_revision: Union[str, None] = 'f25299a1a321'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('practicas', sa.Column('aprobado', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('practicas', 'aprobado')
    # ### end Alembic commands ###
