"""Agregar columna codigo a estudiante

Revision ID: 337a9f1f16df
Revises: 85be6516a8e2
Create Date: 2025-06-16 16:06:56.240079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '337a9f1f16df'
down_revision: Union[str, None] = '85be6516a8e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('estudiantes', sa.Column('codigo', sa.String(), nullable=False, server_default='22012345'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('estudiantes', 'codigo')
    # ### end Alembic commands ###
