"""columna token usuario

Revision ID: 526d608f280b
Revises: f3bf2fea4b10
Create Date: 2025-06-24 18:33:21.385330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '526d608f280b'
down_revision: Union[str, None] = 'f3bf2fea4b10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('token_verificacion', sa.String(), nullable=True,server_default='00'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'token_verificacion')
    # ### end Alembic commands ###
