"""Initial migration

Revision ID: 8559dbb8ce20
Revises: 
Create Date: 2025-05-01 16:44:37.480480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8559dbb8ce20'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'administradores', 'usuarios', ['usuario_id'], ['id'])
    op.create_foreign_key(None, 'empresas', 'usuarios', ['usuario_id'], ['id'])
    op.create_foreign_key(None, 'estudiantes', 'usuarios', ['usuario_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'estudiantes', type_='foreignkey')
    op.drop_constraint(None, 'empresas', type_='foreignkey')
    op.drop_constraint(None, 'administradores', type_='foreignkey')
    # ### end Alembic commands ###
