"""Agregar columnas tabla estudiante

Revision ID: 85be6516a8e2
Revises: dbec75ee3162
Create Date: 2025-06-16 15:33:19.087380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85be6516a8e2'
down_revision: Union[str, None] = 'dbec75ee3162'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('estudiantes', sa.Column('cedula', sa.String(), nullable=False, server_default='0000000000'))
    op.add_column('estudiantes', sa.Column('expedicion_cedula', sa.String(), nullable=True))
    op.add_column('estudiantes', sa.Column('semestre', sa.String(), nullable=False, server_default='8'))
    op.add_column('estudiantes', sa.Column('carrera', sa.String(), nullable=False, server_default='Ingenieria de sistemas'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('estudiantes', 'carrera')
    op.drop_column('estudiantes', 'semestre')
    op.drop_column('estudiantes', 'expedicion_cedula')
    op.drop_column('estudiantes', 'cedula')
    # ### end Alembic commands ###
