"""Agregar modelo de Convenio y campo convenio en Empresa

Revision ID: bb615e761478
Revises: dca8858b8b2f
Create Date: 2025-06-07 16:35:05.903548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb615e761478'
down_revision: Union[str, None] = 'dca8858b8b2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('empresas', sa.Column('convenio', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('empresas', 'convenio')
    # ### end Alembic commands ###
