"""Agregar motivo rechazo

Revision ID: dbec75ee3162
Revises: bb615e761478
Create Date: 2025-06-07 23:13:11.916988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbec75ee3162'
down_revision: Union[str, None] = 'bb615e761478'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('convenios', sa.Column('motivo_rechazo', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('convenios', 'motivo_rechazo')
    # ### end Alembic commands ###
