"""mensaje

Revision ID: dca8858b8b2f
Revises: c1ba96dbeeac
Create Date: 2025-05-25 18:45:49.936328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dca8858b8b2f'
down_revision: Union[str, None] = 'c1ba96dbeeac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('practicas', sa.Column('limite_estudiantes', sa.Integer(), nullable=False, server_default='1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('practicas', 'limite_estudiantes')
    # ### end Alembic commands ###
