"""Agregar columnas para verificacion de usuario

Revision ID: f3bf2fea4b10
Revises: 337a9f1f16df
Create Date: 2025-06-23 20:58:23.871778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3bf2fea4b10'
down_revision: Union[str, None] = '337a9f1f16df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('codigo_verificacion', sa.String(), nullable=True,server_default='000111'))
    op.add_column('usuarios', sa.Column('verificado', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'verificado')
    op.drop_column('usuarios', 'codigo_verificacion')
    # ### end Alembic commands ###
